# Generated by Django 4.0.4 on 2022-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('te', 'telegram'), ('gi', 'github'), ('in', 'instagram'), ('we', 'website')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='owner', to='user.media'),
        ),
    ]
